# Generated by Django 4.0.3 on 2023-07-12 19:24

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 12, 19, 23, 55, 582480, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='note',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
