# Generated by Django 4.0.3 on 2023-07-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_employee_created_at_employee_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='note',
            field=models.TextField(),
        ),
    ]
